"""add passbook_entries

Revision ID: 63f1ff996f58
Revises: d8c1d8da3385
Create Date: 2026-04-16 16:00:48.228046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f1ff996f58'
down_revision: Union[str, Sequence[str], None] = 'd8c1d8da3385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passbook_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('deposited_date', sa.Date(), nullable=False),
    sa.Column('logged_by', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passbook_entries_bank_id'), 'passbook_entries', ['bank_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passbook_entries_bank_id'), table_name='passbook_entries')
    op.drop_table('passbook_entries')
    # ### end Alembic commands ###
