"""add_teller_shifts_table

Revision ID: 8b21747c27c4
Revises: 20599b41879f
Create Date: 2026-04-15 02:48:24.362105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b21747c27c4'
down_revision: Union[str, Sequence[str], None] = '20599b41879f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teller_shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cashier', sa.String(length=50), nullable=False),
    sa.Column('cashier_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='shiftstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_cash_php', sa.Float(), nullable=False),
    sa.Column('closing_cash_php', sa.Float(), nullable=True),
    sa.Column('expected_cash_php', sa.Float(), nullable=True),
    sa.Column('cash_variance', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teller_shifts_cashier'), 'teller_shifts', ['cashier'], unique=False)
    op.create_index(op.f('ix_teller_shifts_date'), 'teller_shifts', ['date'], unique=False)
    op.alter_column('rider_dispatches', 'rider_username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('rider_dispatches', 'status',
               existing_type=postgresql.ENUM('IN_FIELD', 'RETURNED', 'OFF', name='dispatchstatus'),
               nullable=False)
    op.create_index(op.f('ix_rider_dispatches_rider_username'), 'rider_dispatches', ['rider_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rider_dispatches_rider_username'), table_name='rider_dispatches')
    op.alter_column('rider_dispatches', 'status',
               existing_type=postgresql.ENUM('IN_FIELD', 'RETURNED', 'OFF', name='dispatchstatus'),
               nullable=True)
    op.alter_column('rider_dispatches', 'rider_username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_teller_shifts_date'), table_name='teller_shifts')
    op.drop_index(op.f('ix_teller_shifts_cashier'), table_name='teller_shifts')
    op.drop_table('teller_shifts')
    # ### end Alembic commands ###
