"""initial tables

Revision ID: 9240981df8ac
Revises: 
Create Date: 2026-04-12 16:36:41.038764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9240981df8ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('flag', sa.String(length=10), nullable=True),
    sa.Column('category', sa.Enum('MAIN', 'SECOND', 'OTHERS', name='currencycategory'), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('daily_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('carry_in_qty', sa.Float(), nullable=True),
    sa.Column('carry_in_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_positions_currency_code'), 'daily_positions', ['currency_code'], unique=False)
    op.create_index(op.f('ix_daily_positions_date'), 'daily_positions', ['date'], unique=False)
    op.create_table('daily_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('buy_rate', sa.Float(), nullable=False),
    sa.Column('sell_rate', sa.Float(), nullable=False),
    sa.Column('set_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_rates_currency_code'), 'daily_rates', ['currency_code'], unique=False)
    op.create_index(op.f('ix_daily_rates_date'), 'daily_rates', ['date'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('opening_capital', sa.Float(), nullable=False),
    sa.Column('php_cash', sa.Float(), nullable=True),
    sa.Column('total_stock_value', sa.Float(), nullable=True),
    sa.Column('total_capital', sa.Float(), nullable=True),
    sa.Column('total_than', sa.Float(), nullable=True),
    sa.Column('total_bought', sa.Float(), nullable=True),
    sa.Column('total_sold', sa.Float(), nullable=True),
    sa.Column('closed_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_summaries_date'), 'daily_summaries', ['date'], unique=True)
    op.create_table('rider_dispatches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rider_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('dispatch_time', sa.String(length=10), nullable=True),
    sa.Column('cash_php', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rider_dispatches_date'), 'rider_dispatches', ['date'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', name='txntype'), nullable=False),
    sa.Column('source', sa.Enum('COUNTER', 'RIDER', name='txnsource'), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('foreign_amt', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('php_amt', sa.Float(), nullable=False),
    sa.Column('daily_avg_cost', sa.Float(), nullable=False),
    sa.Column('than', sa.Float(), nullable=True),
    sa.Column('cashier', sa.String(length=50), nullable=False),
    sa.Column('customer', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_currency_code'), 'transactions', ['currency_code'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'cashier', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_currency_code'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_rider_dispatches_date'), table_name='rider_dispatches')
    op.drop_table('rider_dispatches')
    op.drop_index(op.f('ix_daily_summaries_date'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_index(op.f('ix_daily_rates_date'), table_name='daily_rates')
    op.drop_index(op.f('ix_daily_rates_currency_code'), table_name='daily_rates')
    op.drop_table('daily_rates')
    op.drop_index(op.f('ix_daily_positions_date'), table_name='daily_positions')
    op.drop_index(op.f('ix_daily_positions_currency_code'), table_name='daily_positions')
    op.drop_table('daily_positions')
    op.drop_table('currencies')
    # ### end Alembic commands ###
